networks:
  ft_services:
    name: ft_services
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      # - "80:80"
      - "443:443"
    networks:
      - ft_services
    init: true
    restart: always
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - ft_services
    init: true
    restart: always