apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      # initContainers:
      # - name: wait-for-mysql
      #   image: busybox:1.36
      #   command:
      #     - sh
      #     - -c
      #     - >
      #       until nc -z mysql 3306;
      #       do echo "Waiting for MySQL..."; sleep 2; done
      containers:
      - name: phpmyadmin
        image: my-phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: global-env
        volumeMounts:
        - name: phpmyadmin-data
          mountPath: /var/www/html
      - name: nginx-phpmyadmin
        image: my-nginx-phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: phpmyadmin-data
          mountPath: /var/www/html
      volumes:
      - name: phpmyadmin-data
        persistentVolumeClaim:
          claimName: phpmyadmin-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
