apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my-wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        envFrom:
        - secretRef:
            name: wordpress-secrets
      - name: wordpress-nginx
        image: my-wordpress-nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
  type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
stringData:
  WP_DB_USER: wp_user
  WP_DB_PASSWORD: wp_password
  WP_ADMIN_PASSWORD: wp_admin_password