apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      # initContainers:
      # - name: wait-for-mysql
      #   image: busybox:1.36
      #   command:
      #     - sh
      #     - -c
      #     - >
      #       until nc -z mysql 3306;
      #       do echo "Waiting for MySQL..."; sleep 2; done
      containers:
      - name: wordpress
        image: my-wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: global-env
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      - name: nginx-wordpress
        image: my-nginx-wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
  type: LoadBalancer